input_schema_template = {'$base': 'https://w3id.org/cwl/cwl#',
 '$graph': [{'$import': 'metaschema_base.yml'},
            {'extends': 'sld:PrimitiveType',
             'name': 'CWLType',
             'symbols': ['cwl:File', 'cwl:Directory'],
             'type': 'enum'},
            {'doc': None,
             'docParent': '#CWLType',
             'fields': [{'jsonldPredicate': {'_id': '@type', '_type': '@vocab'},
                         'name': 'class',
                         'type': {'name': 'File_class',
                                  'symbols': ['cwl:File'],
                                  'type': 'enum'}},
                        {'jsonldPredicate': {'_id': '@id', '_type': '@id'},
                         'name': 'location',
                         'type': 'string?'},
                        {'jsonldPredicate': {'_id': 'cwl:path', '_type': '@id'},
                         'name': 'path',
                         'type': 'string?'},
                        {'jsonldPredicate': 'cwl:basename',
                         'name': 'basename',
                         'type': 'string?'},
                        {'name': 'dirname', 'type': 'string?'},
                        {'name': 'nameroot', 'type': 'string?'},
                        {'name': 'nameext', 'type': 'string?'},
                        {'name': 'checksum', 'type': 'string?'},
                        {'name': 'size', 'type': 'long?'},
                        {'jsonldPredicate': 'cwl:secondaryFiles',
                         'name': 'secondaryFiles',
                         'type': ['null',
                                  {'items': ['File', 'Directory'],
                                   'type': 'array'}]},
                        {'jsonldPredicate': {'_id': 'cwl:format',
                                             '_type': '@id',
                                             'identity': True},
                         'name': 'format',
                         'type': 'string?'},
                        {'name': 'contents', 'type': 'string?'}],
             'name': 'File',
             'type': 'record'},
            {'fields': [{'jsonldPredicate': {'_id': '@type', '_type': '@vocab'},
                         'name': 'class',
                         'type': {'name': 'Directory_class',
                                  'symbols': ['cwl:Directory'],
                                  'type': 'enum'}},
                        {'jsonldPredicate': {'_id': '@id', '_type': '@id'},
                         'name': 'location',
                         'type': 'string?'},
                        {'jsonldPredicate': {'_id': 'cwl:path', '_type': '@id'},
                         'name': 'path',
                         'type': 'string?'},
                        {'jsonldPredicate': 'cwl:basename',
                         'name': 'basename',
                         'type': 'string?'},
                        {'jsonldPredicate': {'_id': 'cwl:listing'},
                         'name': 'listing',
                         'type': ['null',
                                  {'items': ['File', 'Directory'],
                                   'type': 'array'}]}],
             'name': 'Directory',
             'type': 'record'},
            {'documentRoot': True,
             'fields': None,
             'name': 'InputsField',
             'type': 'record'}],
 '$namespaces': {'cwl': 'https://w3id.org/cwl/cwl#',
                 'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
                 'sld': 'https://w3id.org/cwl/salad#'}}

